### PR TITLE
Add the xOpera SaaS plugin to the devfile.

### PR DESCRIPTION
**Pull request by sstanovnik**
/cc @cankarm, @anzoman

Depends on radon-h2020/radon-plugin-registry#3.

### CODE REVIEW

**Comment by cankarm** [comment]
LGTM! I approve for merging.

**Comment by sdagostini** [comment]
@sstanovnik Hi! I have merged the plugin to the RADON devfile but if I run a new RADON workspace I receive this error

> Error: Failed to start the workspace: "Plugin reference URL 'https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-xopera-saas/latest/meta.yaml' is invalid.

It seem that the `meta.yaml` file is missing under the `latest` folder.

**Comment by sstanovnik** [comment]
Yeah, I wanted to be clever and just symlinked `latest` into `0.0.1` like you would usually do, but things don't work that way for GitHub's raw URLs it seems. See radon-h2020/radon-plugin-registry#5 for a PR that just duplicates the spec file.

**Comment by anzoman** [comment]
And I did the same, so here's my PR as well: radon-h2020/radon-plugin-registry#6.

**Pull request merged**
